pipeline {
    agent any

    tools {
        nodejs 'NodeJS22'
    }

    environment {
        IMAGE_NAME = "ebanking-frontend"
        DOCKERHUB_REPO = "hamzaatlili/front"
        VERSION = "${BUILD_NUMBER}" // Chaque build aura un tag unique
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/oussamasebai593/Projet-DigitalBanking-SpringBoot-Angular.git'
            }
        }

        stage('Install dependencies') {
            steps {
                    sh "npm install"
            }
        }

        stage('Build Angular') {
            steps {
                dir('ebanking-frontend') {
                    sh "npm run build"
                }
            }
        }

              stage('Build Docker Image') {
            steps {
                dir('ebanking-frontend') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker stop $IMAGE_NAME || true'
                sh 'docker rm $IMAGE_NAME || true'
                sh 'docker run -d -p 80:80 --name $IMAGE_NAME $IMAGE_NAME'
            }
        }
    
    }
    post {
        success {
            echo '✅ Pipeline terminé avec succès'
        }
        failure {
            echo '❌ Erreur dans le pipeline'
        }
    }
}
