pipeline {
    agent any

    tools {
        nodejs 'NodeJS22'
    }

    stages {


        stage('Debug Structure') {
    steps {
        sh 'ls -la'
        sh 'find . -name package.json'
    }
}

        stage('Install Dependencies') {
            steps {
                dir('ebanking-frontend') {
                    sh 'npm install'
                }
            }
        }

    }

    post {
        always {
            sh 'docker system prune -f'
        }
        success {
            echo '✅ Frontend build et Docker déployé'
        }
        failure {
            echo '❌ Erreur lors du build frontend'
        }
    }
}
