pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven'
    }

    environment {
        SONAR_TOKEN = credentials('Digital Banking backend-token') // token sécurisé pour SonarQube
    }

    stages {

        stage('Checkout') {
            steps {
                echo "🔹 Stage: Checkout"
                git branch: 'main',
                    url: 'https://github.com/oussamasebai593/Projet-DigitalBanking-SpringBoot-Angular.git'
            }
        }

        stage('Build Backend') {
            steps {
                echo "🔹 Stage: Build Backend"
                dir('ebanking-backend') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Run Tests') {
            steps {
                echo "🔹 Stage: Run Tests"
                dir('ebanking-backend') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo "🔹 Stage: SonarQube Analysis"
                dir('ebanking-backend') {
                    withSonarQubeEnv('SonarQubeServer') {
                        sh "mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN}"
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                echo "🔹 Stage: Quality Gate"
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Package') {
            steps {
                echo "🔹 Stage: Package"
                dir('ebanking-backend') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            echo '🔹 Backend pipeline terminé'
        }
        success {
            echo '✅ Backend build + SonarQube OK'
        }
        failure {
            echo '❌ Erreur dans le backend'
        }
    }
}
