pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven'
    }

    environment {
        SONAR_TOKEN = credentials('sonarqube-token')
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/oussamasebai593/Projet-DigitalBanking-SpringBoot-Angular.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('ebanking-backend') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Tests') {
            steps {
                dir('ebanking-backend') {
                    sh 'mvn test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('ebanking-backend') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                        mvn sonar:sonar \
                          -Dsonar.projectKey=DigitalBanking \
                          -Dsonar.login=${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('ebanking-backend') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Backend build + SonarQube OK'
        }
        failure {
            echo '❌ Erreur dans le backend'
        }
    }
}
